on:
  workflow_dispatch:
  push:
    branches:
    - release

jobs:
  release:
    name: "Release to Curseforge"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r addon.zip .
    
      
