on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  
      
  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: "Run Parser"
        id: "parse"
        run: python $PWD"/.github/workflows/scripts/parse_manifest.py"

      - name: "Package"
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r Change_Nametag_${{ github.ref_name }}.mcpack .
        
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: Change_Nametag_${{ github.ref_name }}.mcpack
    
      
