on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  release:
    name: "Release to Curseforge"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r addon.zip .
      - uses: actions/upload-artifact@v4
        with:
          name: addon.zip
    
      
